import styles from "./chess.module.css";

export default function Chess() {
  return (
    <div className={styles.container}>
      <div className={styles.square}>1</div>
      <div className={styles.square}>2</div>
      <div className={styles.square}>3</div>
      <div className={styles.square}>4</div>
      <div className={styles.square}>5</div>
      <div className={styles.square}>6</div>
      <div className={styles.square}>7</div>
      <div className={styles.square}>8</div>
      <div className={styles.square2}>1</div>
      <div className={styles.square2}>2</div>
      <div className={styles.square2}>3</div>
      <div className={styles.square2}>4</div>
      <div className={styles.square2}>5</div>
      <div className={styles.square2}>6</div>
      <div className={styles.square2}>7</div>
      <div className={styles.square2}>8</div>
      <div className={styles.square}>1</div>
      <div className={styles.square}>2</div>
      <div className={styles.square}>3</div>
      <div className={styles.square}>4</div>
      <div className={styles.square}>5</div>
      <div className={styles.square}>6</div>
      <div className={styles.square}>7</div>
      <div className={styles.square}>8</div>
      <div className={styles.square2}>1</div>
      <div className={styles.square2}>2</div>
      <div className={styles.square2}>3</div>
      <div className={styles.square2}>4</div>
      <div className={styles.square2}>5</div>
      <div className={styles.square2}>6</div>
      <div className={styles.square2}>7</div>
      <div className={styles.square2}>8</div>
      <div className={styles.square}>1</div>
      <div className={styles.square}>2</div>
      <div className={styles.square}>3</div>
      <div className={styles.square}>4</div>
      <div className={styles.square}>5</div>
      <div className={styles.square}>6</div>
      <div className={styles.square}>7</div>
      <div className={styles.square}>8</div>
      <div className={styles.square2}>1</div>
      <div className={styles.square2}>2</div>
      <div className={styles.square2}>3</div>
      <div className={styles.square2}>4</div>
      <div className={styles.square2}>5</div>
      <div className={styles.square2}>6</div>
      <div className={styles.square2}>7</div>
      <div className={styles.square2}>8</div>
      <div className={styles.square}>1</div>
      <div className={styles.square}>2</div>
      <div className={styles.square}>3</div>
      <div className={styles.square}>4</div>
      <div className={styles.square}>5</div>
      <div className={styles.square}>6</div>
      <div className={styles.square}>7</div>
      <div className={styles.square}>8</div>
      <div className={styles.square2}>1</div>
      <div className={styles.square2}>2</div>
      <div className={styles.square2}>3</div>
      <div className={styles.square2}>4</div>
      <div className={styles.square2}>5</div>
      <div className={styles.square2}>6</div>
      <div className={styles.square2}>7</div>
      <div className={styles.square2}>8</div>
    </div>
  );
}
